FROM elasticsearch:5.1.1
MAINTAINER Marcel Zeilinger <marcel.zeilinger@live.at>

RUN ./bin/elasticsearch-plugin install analysis-phonetic

RUN ./bin/elasticsearch-plugin install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-analysis-decompound/5.1.1.0/elasticsearch-analysis-decompound-5.1.1.0-plugin.zip
